version: '3.5'

services:
  pass-db:
    image: postgres:${POSTGRES_VERSION}
    restart: always
    env_file: ../../.env.dev
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  pass-adminer:
    image: adminer:latest
    env_file:
      - ../../.env.dev 
    restart: always
    ports:
      - 8080:8080


volumes:
  postgres_data:
