api:
  dashboard: true
  insecure: true

entryPoints:
  adminer:
    address: ":8080"
    proxyProtocol:
      trustedIPs:
        - "127.0.0.1/32"
  
  api:
    http2:
      maxConcurrentStreams: 300
    transport:
      respondingTimeouts:
        readTimeout: "60"
    address: ":3333"
    proxyProtocol:
      trustedIPs:
        - "127.0.0.1/32"
    http:
      redirections:
        entryPoint:
          to: "websecure"
          scheme: "https"
          permanent: true
    
  web:
    address: ":3000"
    transport:
      respondingTimeouts:
        readTimeout: "60"
    proxyProtocol:
      insecure: true
    http:
      redirections:
        entryPoint:
          to: "websecure"
          scheme: "https"
          permanent: true

  websecure:
    address: ":443"
    http:
      tls:
        certResolver: "default"

providers:
  docker:
    watch: true
    exposedByDefault: false
    network: web

certificatesResolvers:
  default:
    acme:
      email: "kmoudery.dev@gmail.com"
      storage: "acme.json"
      caServer: "https://acme-v01.api.letsencrypt.org/directory"
      tlsChallenge:
