version: '3.5'

services:
  pass-db:
    image: postgres:${POSTGRES_VERSION}
    restart: always
    env_file: ../.env.dev
    ports:
      - ${POSTGRES_PORT}:8383
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  pass-adminer:
    image: adminer:latest
    env_file:
      - ../.env.dev 
    restart: always
    ports:
      - ${ADMINER_PORT}:8380


volumes:
  postgres_data:
